### ISSUE TITLE
compatible with ie7?

### ISSUE THREAD

**Issue by sueki** [KevinBatdorf/codaslider#39]
it seems like coda-slider is NOT compatible with ie7. Isn't it?

**Comment by pixelismo** [comment]
sorry for my english.
i'm having problems on explorer 7/6
the overflow:hidden seems tobe one of the problems.
if you see it in chrome or another one, it see it perfect. http://www.zbv.com.ar/
but explorer 7 looks like this print screen
![captura de pantalla](https://cloud.githubusercontent.com/assets/6282700/10059093/67aaa260-621f-11e5-9869-234b10540b73.jpg)

i wish someone can help me with this.

Thank You!

**Comment by KevinBatdorf** [comment]
How does it look in IE 5 or IE 4? You don't want to support those too? ;-)

In short, if you still need to support very old, outdated browsers you need to learn how to fix issues like this yourself. Good luck.
