### ISSUE TITLE
There is no git tags on GitHub repository

### ISSUE THREAD

**Issue by sufuf3** [KevinBatdorf/codaslider#53]
Hi @KevinBatdorf ,
We are cdnjs team, we're going to host this library.
The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [**git tags**](https://github.com/KevinBatdorf/codaslider/tags) so that it can recognize the correct version and automatically update the repo.
Could you please add git tags for the repo? Thank you.

[cdnjs/cdnjs#10571](https://github.com/cdnjs/cdnjs/issues/10571)

**Comment by KevinBatdorf** [comment]
Added a tag. This is an old repo though. Not sure it's that relevant to use anymore. There's a newer version (which is also slightly dated already) [here](https://github.com/KevinBatdorf/liquidslider).

**Comment by sufuf3** [comment]
@KevinBatdorf Thank you.
