### ISSUE TITLE
Speed of slider is so slow

### ISSUE THREAD

**Issue by Wasim12378** [KevinBatdorf/codaslider#54]
I am using this slider here https://dev.sandiegovets.com/faq/ and when i click on tabs the slider is stucked and work so slow .. Can you tell me to make it speedy ?

**Comment by KevinBatdorf** [comment]
@Wasim12378 You have the wrong project. That code has a similar name but isn't this. 

You should contact the theme developer for your WordPress theme.

**Comment by Wasim12378** [comment]
I am using it custom .. i pick the slider and have integrated in this theme . so its exactly ur slider

**Comment by KevinBatdorf** [comment]
This is the code I see on your site: 

https://dev.sandiegovets.com/wp-content/themes/revolution-new/extrafiles/coda-slider.js

Compare it to the code from this project:

https://github.com/KevinBatdorf/codaslider/blob/master/js/jquery.coda-slider-3.0.js
